<?php
$oodleFieldValues=array("looking_for_gender_both"=>"Both","looking_for_gender_men"=>"Men","looking_for_gender_other"=>"Other","looking_for_gender_women"=>"Women",
"looking_for_type_casual_encounters"=>"Casual Encounters","looking_for_type_dating"=>"Dating","looking_for_type_friends"=>"Friends","looking_for_type_marriage"=>"Marriage",
"looking_for_type_relationship"=>"Relationship"
);

                    
$oodleFields=array(" "=>"--None--","id"=>"ID","ctime"=>"Date","title"=>"Title","body"=>"Description","price"=>"Price",
"url"=>"URL","ad_type"=>"Type of Listing","age_range"=>"Age Range",
"amenities"=>"Amenities","apartment_community"=>"Apartment Community",
"bathrooms"=>"Bathrooms","bedrooms"=>"Bedrooms",
"brand"=>"Brand","color"=>"Color",
"company"=>"Company","condition"=>"Condition",
"deal_type"=>"Deal Type","dealer_id"=>"Dealer Name",
"delivery"=>"Delivery Options","discipline"=>"Discipline (type of horse)",
"drink"=>"Drinks","employee_type"=>"Employee Type",
"engine_type"=>"Engine Type","ethnicity"=>"Ethnicity",
"event"=>"Event Name","event_date"=>"Event Date",
"event_location"=>"Event Location","event_venue"=>"Event Venue",
"eye_color"=>"Eye Color","family_friendly"=>"Event Family Friendly",
"features"=>"Vehicle Features","fee"=>"Fee",
"full_time"=>"Full Time","gender"=>"Gender",
"hair_color"=>"Hair Color","has_photo"=>"Has Photo",
"have_kids"=>"Has Kids","house_type"=>"House Type",
"industry"=>"Industry","interests"=>"Interests",
"job_title"=>"Job Title","languages"=>"Spoken Languages",
"looking_for_gender"=>"Looking for Gender","looking_for_keywords"=>"Looking for Keywords",
"looking_for_type"=>"Looking for Relationship","lot_size"=>"Lot Size",
"make"=>"Vehicle Make","marital_status"=>"Marital Status",
"mens_womens"=>"Clothing Men or Women","mileage"=>"Vehicle Mileage",
"miles_per_gallon"=>"Vehicle MPG","model"=>"Vehicle Model",
"pet_age"=>"Pet Age","pet_breed"=>"Pet Breed",
"pets_allowed"=>"Pets Allowed",
"private_party"=>"Posted by Private Party","redeemable"=>"Coupon Redeemable",
"religion"=>"Religion","seller_type"=>"Seller Type",
"sex"=>"Pet Gender","size"=>"Size",
"smoke"=>"Smoker","square_feet"=>"Square Feet",
"store"=>"Store Name","team"=>"Team Name",
"transmission"=>"Vehicle Transmission","trim"=>"Vehicle Trime",
"want_kids"=>"Wants Kids","year"=>"Year Manufactured",
"zodiac"=>"Zodiac Sign"
);

$oodleRegions=array("canada"=>array("abbotsford"=>"Abbotsford","barrie"=>"Barrie"
,"brantford"=>"Brantford","calgary"=>"Calgary"
,"charlottetown"=>"Charlottetown","chathamkent"=>"Chatham-Kent"
,"edmonton"=>"Edmonton","guelph"=>"Guelph"
,"halifaxns"=>"Halifax","hamilton"=>"Hamilton"
,"iqaluit"=>"Iqaluit","kelowna"=>"Kelowna"
,"kingstonon"=>"Kingston","kitchener"=>"Kitchener"
,"londonon"=>"London, ON","moncton"=>"Moncton"
,"montreal"=>"Montreal","oshawa"=>"Oshawa"
,"ottawa"=>"Ottawa-Gatineau","peterboroughcan"=>"Peterborough"
,"quebec"=>"Quebec City","regina"=>"Regina"
,"saguenay"=>"Saguenay","saintjohn"=>"Saint John"
,"saskatoon"=>"Saskatoon","sherbrooke"=>"Sherbrooke"
,"niagara"=>"St. Catharines-Niagara","stjohns"=>"St. John's"
,"sudbury"=>"Sudbury","thunderbay"=>"Thunder Bay"
,"toronto"=>"Toronto","troisrivieres"=>"Trois-Rivieres"
,"vancouver"=>"Vancouver","victoria"=>"Victoria"
,"whitehorse"=>"Whitehorse","windsor"=>"Windsor"
,"winnipeg"=>"Winnipeg","yellowknife"=>"Yellowknife"),
"uk"=>array("aberdeen"=>"Aberdeen","barnsley"=>"Barnsley",
"bath"=>"Bath","belfast"=>"Belfast","birminghamgb"=>"Birmingham",
"blackburn"=>"Blackburn","blackpool"=>"Blackpool",
"bolton"=>"Bolton","bournemouth"=>"Bournemouth",
"bradford"=>"Bradford","brighton"=>"Brighton",
"bristol"=>"Bristol","bromley"=>"Bromley",
"cambridge"=>"Cambridge","canterbury"=>"Canterbury",
"cardiff"=>"Cardiff","carlisle"=>"Carlisle",
"chelmsford"=>"Chelmsford","chester"=>"Chester",
"colchester"=>"Colchester","coventry"=>"Coventry",
"crewe"=>"Crewe","croydon"=>"Croydon",
"darlington"=>"Darlington","dartford"=>"Dartford",
"derby"=>"Derby","doncaster"=>"Doncaster",
"dorchester"=>"Dorchester","dudley"=>"Dudley",
"dumfries"=>"Dumfries","dundee"=>"Dundee",
"durham"=>"Durham","edinburgh"=>"Edinburgh",
"enfield"=>"Enfield","england"=>"England",
"exeter"=>"Exeter","falkirk"=>"Falkirk",
"galashiels"=>"Galashiels","glasgow"=>"Glasgow",
"gloucester"=>"Gloucester","guildford"=>"Guildford",
"halifax"=>"Halifax","harrogate"=>"Harrogate",
"harrow"=>"Harrow","hemelhempstead"=>"Hemel Hempstead",
"hereford"=>"Hereford","huddersfield"=>"Huddersfield",
"hull"=>"Hull","ilford"=>"Ilford",
"inverness"=>"Inverness","ipswich"=>"Ipswich",
"kilmarnock"=>"Kilmarnock","kingston"=>"Kingston upon Thames",
"kirkcaldy"=>"Kirkcaldy","kirkwall"=>"Kirkwall",
"lancastergb"=>"Lancaster","leeds"=>"Leeds",
"leicester"=>"Leicester","lerwick"=>"Lerwick",
"lincolngb"=>"Lincoln","liverpool"=>"Liverpool",
"llandrindodwells"=>"Llandrindod Wells","llandudno"=>"Llandudno",
"london"=>"London","luton"=>"Luton","manchester"=>"Manchester",
"medway"=>"Medway","middlesbrough"=>"Middlesbrough",
"miltonkeynes"=>"Milton Keynes","motherwell"=>"Motherwell",
"newcastle"=>"Newcastle","newport"=>"Newport",
"northampton"=>"Northampton","nireland"=>"Northern Ireland",
"norwich"=>"Norwich","nottingham"=>"Nottingham",
"oldham"=>"Oldham","oxford"=>"Oxford",
"paisley"=>"Paisley","perthgb"=>"Perth",
"peterborough"=>"Peterborough","plymouth"=>"Plymouth",
"portsmouth"=>"Portsmouth","preston"=>"Preston",
"reading"=>"Reading","redhill"=>"Redhill",
"richmondgb"=>"Richmond","romford"=>"Romford",
"rotherham"=>"Rotherham","salisbury"=>"Salisbury",
"scotland"=>"Scotland","sheffield"=>"Sheffield",
"shrewsbury"=>"Shrewsbury","slough"=>"Slough",
"southall"=>"Southall","southampton"=>"Southampton",
"southend"=>"Southend","stalbans"=>"St. Albans",
"stevenage"=>"Stevenage","stockport"=>"Stockport",
"stoke"=>"Stoke-on-Trent","sunderland"=>"Sunderland",
"sutton"=>"Sutton","swansea"=>"Swansea","swindon"=>"Swindon",
"taunton"=>"Taunton","telford"=>"Telford","torquay"=>"Torquay",
"truro"=>"Truro","tunbridge"=>"Tunbridge Wells","wakefield"=>"Wakefield",
"wales"=>"Wales","walsall"=>"Walsall",
"warrington"=>"Warrington","watford"=>"Watford",
"wigan"=>"Wigan","wolverhampton"=>"Wolverhampton",
"worcester"=>"Worcester","york"=>"York"),
"usa"=>array("abilene"=>"Abilene, TX","albany"=>"Albany, NY",
"albanyga"=>"Albany, GA","albuquerque"=>"Albuquerque, NM",
"alexandriala"=>"Alexandria, LA","allentown"=>"Allentown, PA",
"altoona"=>"Altoona, PA","amarillo"=>"Amarillo, TX",
"anchorage"=>"Anchorage, AK","annistonal"=>"Anniston, AL",
"appleton"=>"Appleton, WI","asheville"=>"Asheville, NC",
"athensga"=>"Athens, GA","atlanta"=>"Atlanta, GA",
"atlanticcity"=>"Atlantic City, NJ","auburn"=>"Auburn, AL",
"augusta"=>"Augusta, GA","austin"=>"Austin, TX",
"bakersfield"=>"Bakersfield, CA","baltimore"=>"Baltimore, MD",
"bangorme"=>"Bangor, ME","barnstablema"=>"Barnstable, MA",
"batonrouge"=>"Baton Rouge, LA","beaumont"=>"Beaumont, TX",
"bellingham"=>"Bellingham, WA","bentonharbor"=>"Benton Harbor, MI",
"billings"=>"Billings, MT","biloxi"=>"Biloxi, MS",
"binghamton"=>"Binghamton, NY","birmingham"=>"Birmingham, AL",
"bismarck"=>"Bismarck, ND","bloomington"=>"Bloomington, IL",
"bloomingtonin"=>"Bloomington, IN","boise"=>"Boise, ID",
"boston"=>"Boston, MA","brownsville"=>"Brownsville, TX",
"bryantx"=>"Bryan, TX","buffalo"=>"Buffalo, NY",
"burlington"=>"Burlington, VT","canton"=>"Canton, OH",
"casper"=>"Casper, WY","cedarrapids"=>"Cedar Rapids, IA",
"champaign"=>"Champaign, IL","charleston"=>"Charleston, SC",
"charlestonwv"=>"Charleston, WV","charlotte"=>"Charlotte, NC",
"charlottesville"=>"Charlottesville, VA","chattanooga"=>"Chattanooga, TN",
"cheyenne"=>"Cheyenne, WY","chicago"=>"Chicago, IL",
"chico"=>"Chico, CA","cincinnati"=>"Cincinnati, OH",
"clarksvilletn"=>"Clarksville, TN","cleveland"=>"Cleveland, OH",
"coloradosprings"=>"Colorado Springs, CO","columbiamo"=>"Columbia, MO",
"columbia"=>"Columbia, SC","columbus"=>"Columbus, OH",
"columbusga"=>"Columbus, GA","corpuschristi"=>"Corpus Christi, TX",
"corvallis"=>"Corvallis, OR","cumberland"=>"Cumberland, MD",
"dallas"=>"Dallas, TX","danvilleva"=>"Danville, VA",
"davenport"=>"Davenport, IA","dayton"=>"Dayton, OH",
"daytonabeach"=>"Daytona Beach, FL","decatural"=>"Decatur, AL",
"decaturil"=>"Decatur, IL","denver"=>"Denver, CO",
"desmoines"=>"Des Moines, IA","detroit"=>"Detroit, MI",
"dothan"=>"Dothan, AL","doverde"=>"Dover, DE",
"dubuque"=>"Dubuque, IA","duluth"=>"Duluth, MN",
"eauclaire"=>"Eau Claire, WI","elpaso"=>"El Paso, TX",
"elkhart"=>"Elkhart, IN","elmira"=>"Elmira, NY",
"enidok"=>"Enid, OK","erie"=>"Erie, PA",
"eugene"=>"Eugene, OR","evansville"=>"Evansville, IN",
"fargo"=>"Fargo, ND","fayettevillear"=>"Fayetteville, AR",
"fayettevillenc"=>"Fayetteville, NC","flagstaff"=>"Flagstaff, AZ",
"florenceal"=>"Florence, AL","florencesc"=>"Florence, SC",
"fortcollins"=>"Fort Collins, CO","fortmyers"=>"Fort Myers, FL",
"fortpierce"=>"Fort Pierce, FL","fortsmith"=>"Fort Smith, AR",
"ftwaltonbeach"=>"Fort Walton Beach, FL","fortwayne"=>"Fort Wayne, IN",
"fresno"=>"Fresno, CA","gadsden"=>"Gadsden, AL",
"gainesville"=>"Gainesville, FL","glensfalls"=>"Glens Falls, NY",
"goldsboronc"=>"Goldsboro, NC","grandforks"=>"Grand Forks, ND",
"grandjunction"=>"Grand Junction, CO","grandrapids"=>"Grand Rapids, MI",
"greatfalls"=>"Great Falls, MT","greenbay"=>"Green Bay, WI",
"greensboro"=>"Greensboro, NC","greenvillenc"=>"Greenville, NC",
"greenville"=>"Greenville, SC","harrisburg"=>"Harrisburg, PA",
"hartford"=>"Hartford, CT","hattiesburg"=>"Hattiesburg, MS",
"hendersonville"=>"Hendersonville, NC","hickory"=>"Hickory, NC",
"honolulu"=>"Honolulu, HI","houma"=>"Houma, LA",
"houston"=>"Houston, TX","huntingtonwv"=>"Huntington, WV",
"huntsville"=>"Huntsville, AL","indianapolis"=>"Indianapolis, IN",
"iowacity"=>"Iowa City, IA","jacksonmi"=>"Jackson, MI",
"jackson"=>"Jackson, MS","jacksontn"=>"Jackson, TN",
"jacksonville"=>"Jacksonville, FL","jacksonvillenc"=>"Jacksonville, NC",
"jamestownny"=>"Jamestown, NY","janesville"=>"Janesville, WI",
"johnsoncity"=>"Johnson City, TN","johnstown"=>"Johnstown, PA",
"jonesboro"=>"Jonesboro, AR","joplin"=>"Joplin, MO",
"kalamazoo"=>"Kalamazoo, MI","kc"=>"Kansas City, MO",
"killeen"=>"Killeen, TX","knoxville"=>"Knoxville, TN",
"kokomo"=>"Kokomo, IN","lacrosse"=>"La Crosse, WI",
"lafayettein"=>"Lafayette, IN","lafayettela"=>"Lafayette, LA",
"lakecharles"=>"Lake Charles, LA","lakeland"=>"Lakeland, FL",
"lancaster"=>"Lancaster, PA","lansing"=>"Lansing, MI",
"laredo"=>"Laredo, TX","lascruces"=>"Las Cruces, NM",
"lasvegas"=>"Las Vegas, NV","lawrenceks"=>"Lawrence, KS",
"lawtonok"=>"Lawton, OK","lewistonme"=>"Lewiston, ME",
"lexington"=>"Lexington, KY","lima"=>"Lima, OH",
"lincoln"=>"Lincoln, NE","littlerock"=>"Little Rock, AR",
"longviewtx"=>"Longview, TX","la"=>"Los Angeles, CA",
"louisville"=>"Louisville, KY","lubbock"=>"Lubbock, TX",
"lynchburg"=>"Lynchburg, VA","macon"=>"Macon, GA",
"madison"=>"Madison, WI","manchesternh"=>"Manchester, NH",
"mansfieldoh"=>"Mansfield, OH","mcallen"=>"McAllen, TX",
"medford"=>"Medford, OR","melbournefl"=>"Melbourne, FL",
"memphis"=>"Memphis, TN","merced"=>"Merced, CA",
"meridian"=>"Meridian, MS","miami"=>"Miami, FL",
"milwaukee"=>"Milwaukee, WI","minneapolis"=>"Minneapolis, MN",
"missoula"=>"Missoula, MT","mobileal"=>"Mobile, AL",
"modesto"=>"Modesto, CA","monroela"=>"Monroe, LA",
"montgomery"=>"Montgomery, AL","muncie"=>"Muncie, IN",
"myrtlebeach"=>"Myrtle Beach, SC","naples"=>"Naples, FL",
"nashville"=>"Nashville, TN","natchez"=>"Natchez, MS",
"newlondon"=>"New London, CT","neworleans"=>"New Orleans, LA",
"ny"=>"New York, NY","newark"=>"Newark, NJ",
"norfolk"=>"Norfolk, VA","ocala"=>"Ocala, FL",
"odessa"=>"Odessa, TX","oklahomacity"=>"Oklahoma City, OK",
"omaha"=>"Omaha, NE","orlando"=>"Orlando, FL",
"owensboro"=>"Owensboro, KY","panamacity"=>"Panama City, FL",
"parkersburg"=>"Parkersburg, WV","pensacola"=>"Pensacola, FL",
"peoria"=>"Peoria, IL","philly"=>"Philadelphia, PA",
"phoenix"=>"Phoenix, AZ","pinebluff"=>"Pine Bluff, AR",
"pittsburgh"=>"Pittsburgh, PA","pittsfieldma"=>"Pittsfield, MA",
"pocatello"=>"Pocatello, ID","portcharlotte"=>"Port Charlotte, FL",
"portland"=>"Portland, OR","portlandme"=>"Portland, ME",
"providence"=>"Providence, RI","provo"=>"Provo, UT",
"pueblo"=>"Pueblo, CO","puntagorda"=>"Punta Gorda, FL",
"raleigh"=>"Raleigh, NC","rapidcity"=>"Rapid City, SD",
"readingpa"=>"Reading, PA","redding"=>"Redding, CA",
"reno"=>"Reno, NV","richlandwa"=>"Richland, WA",
"richmond"=>"Richmond, VA","roanoke"=>"Roanoke, VA",
"rochester"=>"Rochester, NY","rochestermn"=>"Rochester, MN",
"rockfordil"=>"Rockford, IL","rockymount"=>"Rocky Mount, NC",
"sacramento"=>"Sacramento, CA","saginaw"=>"Saginaw, MI",
"salinas"=>"Salinas, CA","saltlakecity"=>"Salt Lake City, UT",
"sanangelo"=>"San Angelo, TX","sanantonio"=>"San Antonio, TX",
"sandiego"=>"San Diego, CA","sf"=>"San Francisco, CA",
"sanluisobispo"=>"San Luis Obispo, CA","santabarbara"=>"Santa Barbara, CA",
"santafe"=>"Santa Fe, NM","sarasota"=>"Sarasota, FL",
"savannah"=>"Savannah, GA","scranton"=>"Scranton, PA",
"seattle"=>"Seattle, WA","sebring"=>"Sebring, FL",
"sharonpa"=>"Sharon, PA","sheboygan"=>"Sheboygan, WI",
"shermantx"=>"Sherman, TX","shreveport"=>"Shreveport, LA",
"siouxcity"=>"Sioux City, IA","siouxfalls"=>"Sioux Falls, SD",
"southbend"=>"South Bend, IN","spokane"=>"Spokane, WA",
"springfieldil"=>"Springfield, IL","springfieldma"=>"Springfield, MA",
"springfieldmo"=>"Springfield, MO","stlouis"=>"St Louis, MO",
"stcloud"=>"St. Cloud, MN","stjosephmo"=>"St. Joseph, MO",
"statecollege"=>"State College, PA","steubenville"=>"Steubenville, OH",
"stockton"=>"Stockton, CA","sumtersc"=>"Sumter, SC",
"syracuse"=>"Syracuse, NY","tallahassee"=>"Tallahassee, FL",
"tampa"=>"Tampa, FL","terrehaute"=>"Terre Haute, IN",
"texarkana"=>"Texarkana, TX","thevillages"=>"The Villages, FL",
"toccoa"=>"Toccoa, GA","toledo"=>"Toledo, OH",
"topeka"=>"Topeka, KS","trenton"=>"Trenton, NJ",
"tucson"=>"Tucson, AZ","tulsa"=>"Tulsa, OK",
"tuscaloosa"=>"Tuscaloosa, AL","tylertx"=>"Tyler, TX",
"utica"=>"Utica, NY","victoriatx"=>"Victoria, TX",
"visalia"=>"Visalia, CA","waco"=>"Waco, TX",
"dc"=>"Washington, DC","waterlooia"=>"Waterloo, IA",
"wausau"=>"Wausau, WI","westpalmbeach"=>"West Palm Beach, FL",
"wheeling"=>"Wheeling-Steubenville, WV","wichita"=>"Wichita, KS",
"wichitafallstx"=>"Wichita Falls, TX","williamsportpa"=>"Williamsport, PA",
"wilmington"=>"Wilmington, NC","winstonsalem"=>"Winston-Salem, NC",
"winterhaven"=>"Winter Haven, FL","woodbridge"=>"Woodbridge, VA",
"yakima"=>"Yakima, WA","yorkpa"=>"York, PA",
"youngstown"=>"Youngstown, OH","yubacity"=>"Yuba City, CA",
"yuma"=>"Yuma, AZ"),
"india"=>Array("ahmedabad"=>"Ahmedabad","bangalore"=>"Bangalore",
"bhopal"=>"Bhopal","chennai"=>"Chennai","delhi"=>"Delhi",
"hyderabad"=>"Hyderabad","indore"=>"Indore","jaipur"=>"Jaipur",
"kanpur"=>"Kanpur","kolkata"=>"Kolkata","lucknow"=>"Lucknow",
"mumbai"=>"Mumbai","nagpur"=>"Nagpur","patna"=>"Patna",
"pune"=>"Pune","surat"=>"Surat"),
"ireland"=>Array("cork"=>"Cork","dublin"=>"Dublin","galway"=>"Galway",
"limerick"=>"Limerick","waterford"=>"Waterford")
);

$oodleCategories=array(
"Property_For_Rent"=>array(
    "housing/rent"=>"Property For Rent",
    "housing/rent/apartment"=>"Apartments for Rent",
    "housing/rent/commercial"=>"Commercial & Office Space for Rent",
    "housing/rent/commercial/office_space"=>"Office Space for Rent",
    "housing/rent/condo"=>"Condos & Townhouses for Rent",
    "housing/rent/garage"=>"Garages for Rent",
    "housing/rent/home"=>"Homes for Rent",
    "housing/rent/mobile"=>"Mobile Homes for Rent",
    "housing/rent/open_house"=>"Open Houses for Rent",
    "housing/rent/other"=>"Other Housing for Rent",
    "housing/rent/roommates"=>"Roommates",
    "housing/rent/short_term"=>"Short Term Rentals",
    "housing/rent/storage"=>"Storage Space for Rent",
    "housing/rent/vacation"=>"Vacation Rentals"),
"Real_Estate"=>array(    
    "housing/sale"=>"Real Estate",
    "housing/sale/commercial"=>"Commercial & Office Space for Sale",
    "housing/sale/commercial/office_space"=>"Office Space for Sale",
    "housing/sale/condo"=>"Condos, Townhouses & Apts for Sale",
    "housing/sale/farm"=>"Farms & Ranches for Sale",
    "housing/sale/foreclosure"=>"Foreclosures",
    "housing/sale/home"=>"Single-Family Houses",
    "housing/sale/land"=>"Land for Sale",
    "housing/sale/mobile"=>"Mobile Homes for Sale",
    "housing/sale/multi_family"=>"Multi-Family Residences for Sale",
    "housing/sale/open_house"=>"Open Houses",
    "housing/sale/other"=>"Other Housing for Sale",
    "housing/sale/storage"=>"Storage Space for Sale",
    "housing/sale/vacation"=>"Vacation Property for Sale"),
"Jobs"=>array(
    "job"=>"Jobs",
    "job/admin"=>"Administrative, Clerical & Support Services Jobs",
    "job/advertising"=>"Advertising, Marketing & Public Relations Jobs",
    "job/architecture"=>"Architecture & Design Jobs",
    "job/art"=>"Art, Media & Writer Jobs",
    "job/art/other"=>"Other Art & Media Jobs",
    "job/art/visual_art"=>"Visual Art Jobs",
    "job/art/writing"=>"Writing Jobs",
    "job/civil_service"=>"Civil Service & Public Policy Jobs",
    "job/construction"=>"Construction & Skilled Labor Jobs",
    "job/customer_service"=>"Customer Service & Call Center Jobs",
    "job/domestic_help"=>"Domestic Help, Child & Adult Care Jobs",
    "job/education"=>"Teaching, Training & Library Jobs",
    "job/energy"=>"Oil, Gas & Solar Power Jobs",
    "job/engineer"=>"Engineering & Product Development Jobs",
    "job/entertainment"=>"TV, Film & Musician Jobs",
    "job/entertainment/actor"=>"Acting Jobs",
    "job/entertainment/actor/adult"=>"Adult Acting Jobs",
    "job/entertainment/dancer"=>"Dancing Jobs",
    "job/entertainment/dancer/adult"=>"Adult Dancing Jobs",
    "job/entertainment/model"=>"Modeling Jobs",
    "job/entertainment/model/adult"=>"Adult Modeling Jobs",
    "job/entertainment/music"=>"Music Jobs",
    "job/entertainment/post_production"=>"Post-Production Jobs",
    "job/entertainment/production"=>"Production Jobs",
    "job/facilities"=>"Facilities & Maintenance Jobs",
    "job/finance"=>"Accounting & Finance Jobs",
    "job/general_labor"=>"General Labor & Warehouse Jobs",
    "job/health"=>"Healthcare & Nurse Jobs",
    "job/hospitality"=>"Hospitality, Tourism & Travel Jobs",
    "job/hr"=>"Human Resources & Recruiting Jobs",
    "job/law_enforcement"=>"Law Enforcement & Security Jobs",
    "job/legal"=>"Legal Jobs",
    "job/logistics"=>"Transportation, Travel & Logistics Jobs",
    "job/management"=>"Management & Executive Jobs",
    "job/nonprofit"=>"Non-Profit & Fundraising Jobs",
    "job/other"=>"Other Jobs",
    "job/production_operation"=>"Production & Operations Jobs",
    "job/qa"=>"Quality Assurance & Control Jobs",
    "job/rd"=>"Research & Development Jobs",
    "job/real_estate"=>"Real Estate Jobs",
    "job/retail"=>"Retail, Grocery & Wholesale Jobs",
    "job/sales"=>"Sales & Business Development Jobs",
    "job/salon"=>"Salon, Fitness & Spa Jobs",
    "job/science"=>"Science, Pharmaceutical & Biotech Jobs",
    "job/social_services"=>"Social Services & Counseling Jobs",
    "job/tech"=>"Computer& Software Jobs",
    "job/vet"=>"Veterinary & Other Animal Care Jobs",
    "job/work_from_home"=>"Work from Home & Self Employed Jobs"),
"Personals"=>array(
    "personals"=>"Personals",
    "personals/men_seeking_both"=>"Men Seeking Both",
    "personals/men_seeking_men"=>"Men Seeking Men",
    "personals/men_seeking_women"=>"Men Seeking Women",
    "personals/missed_connections"=>"Missed Connections",
    "personals/other"=>"Everyone Else",
    "personals/women_seeking_both"=>"Women Seeking Both",
    "personals/women_seeking_men"=>"Women Seeking Men",
    "personals/women_seeking_women"=>"Women Seeking Women"),
"Items_for_Sale"=>array(
    "sale"=>"Items for Sale",
    "sale/book"=>"Books & Magazines",
    "sale/book/audio"=>"Audio Books",
    "sale/book/books"=>"Books",
    "sale/book/kids"=>"Kids Books",
    "sale/book/magazine"=>"Magazines",
    "sale/book/manual"=>"Books: Manuals",
    "sale/book/textbook"=>"Textbooks",
    "sale/business"=>"Office & Business",
    "sale/business/building"=>"Building Supplies",
    "sale/business/farm"=>"Agriculture & Forestry",
    "sale/business/medical"=>"Medical Equip & Supplies",
    "sale/business/office"=>"Office Equip & Supplies",
    "sale/business/retail"=>"Restaurant & Retail",
    "sale/business/sale"=>"Business for Sale",
    "sale/clothes"=>"Clothes & Accessories",
    "sale/clothes/accessories"=>"Accessories",
    "sale/clothes/accessories/backpack"=>"Backpacks & Briefcases",
    "sale/clothes/accessories/belt"=>"Belts",
    "sale/clothes/accessories/glove"=>"Gloves & Mittens",
    "sale/clothes/accessories/hair"=>"Hair Accessories",
    "sale/clothes/accessories/hats"=>"Hats & Caps",
    "sale/clothes/accessories/luggage"=>"Luggage",
    "sale/clothes/accessories/neckware"=>"Neckware, Ties & Scarfs",
    "sale/clothes/accessories/sunglasses"=>"Sunglasses",
    "sale/clothes/accessories/wallet"=>"Wallets, Purses & Handbags",
    "sale/clothes/coats"=>"Coats, Parkas & Wind Breakers",
    "sale/clothes/dresses"=>"Dresses",
    "sale/clothes/exercise"=>"Exercise & Fitness Clothes",
    "sale/clothes/jewelry"=>"Jewelry",
    "sale/clothes/jewelry/bracelet"=>"Bracelets",
    "sale/clothes/jewelry/earring"=>"Earrings",
    "sale/clothes/jewelry/necklace"=>"Necklaces",
    "sale/clothes/jewelry/ring"=>"Rings",
    "sale/clothes/jewelry/watch"=>"Watches",
    "sale/clothes/military"=>"Military Gear & Surplus",
    "sale/clothes/other"=>"Other Clothing",
    "sale/clothes/outfits"=>"Outfits & Sets",
    "sale/clothes/pants"=>"Pants & Jeans",
    "sale/clothes/shirts"=>"Shirts & Tops",
    "sale/clothes/shoes"=>"Shoes",
    "sale/clothes/shorts"=>"Shorts",
    "sale/clothes/skirts"=>"Skirts",
    "sale/clothes/sleepwear"=>"Sleepwear & Underwear",
    "sale/clothes/socks"=>"Socks & Hosiery",
    "sale/clothes/suits"=>"Suits, Blazers & Jackets",
    "sale/clothes/sweater"=>"Sweaters",
    "sale/clothes/swimming"=>"Swimwear",
    "sale/clothes/wedding"=>"Wedding Clothes & Accessories",
    "sale/collectible"=>"Collectibles",
    "sale/collectible/antiques"=>"Antique Collectibles",
    "sale/collectible/art"=>"Art",
    "sale/collectible/cards"=>"Trading Cards",
    "sale/collectible/coins"=>"Coins",
    "sale/collectible/comics"=>"Comics",
    "sale/collectible/military"=>"Military Memorabilia",
    "sale/collectible/sports"=>"Sports Memorabilia",
    "sale/collectible/stamps"=>"Stamps",
    "sale/computer"=>"Computers & Accessories",
    "sale/computer/component"=>"Computer Components",
    "sale/computer/computer"=>"Computers",
    "sale/computer/computer/desktop"=>"Desktop PCs",
    "sale/computer/computer/laptop"=>"Laptop Computers",
    "sale/computer/computer/server"=>"Computer Servers",
    "sale/computer/input"=>"Computer Input Devices",
    "sale/computer/input/keyboard"=>"Computer Keyboards",
    "sale/computer/input/mouse"=>"Computer Mouse",
    "sale/computer/monitor"=>"Computer Monitors",
    "sale/computer/monitor/crt"=>"CRT Monitors",
    "sale/computer/monitor/lcd"=>"LCD Monitors",
    "sale/computer/network"=>"Computer Networking",
    "sale/computer/network/hub"=>"Computer Hubs",
    "sale/computer/network/load_balancer"=>"Computer Load Balancers",
    "sale/computer/network/other"=>"Other Networking Equipment",
    "sale/computer/network/router"=>"Computer Routers",
    "sale/computer/network/switch"=>"Computer Switches",
    "sale/computer/network/wifi"=>"Wireless Networking",
    "sale/computer/other"=>"Other Computer Equipment",
    "sale/computer/printer"=>"Printers, Supplies & Accessories",
    "sale/computer/printer/all"=>"All-in-One Printers",
    "sale/computer/printer/inkjet"=>"Inkjet Printers",
    "sale/computer/printer/laser"=>"Laser Printers",
    "sale/computer/printer/supply"=>"Printer Supplies",
    "sale/computer/scanner"=>"Scanners",
    "sale/computer/software"=>"Computer Software",
    "sale/computer/storage"=>"Computer Storage",
    "sale/computer/storage/cd"=>"CD Drives",
    "sale/computer/storage/dvd"=>"DVD Drives",
    "sale/computer/storage/flash"=>"Flash Memory Drives",
    "sale/computer/storage/floppy"=>"Floppy Drives",
    "sale/computer/storage/hard"=>"Hard Drives",
    "sale/computer/storage/hard/external"=>"External Hard Drives",
    "sale/computer/storage/hard/internal"=>"Internal Hard Drives",
    "sale/computer/storage/media"=>"Blank Media",
    "sale/electronics"=>"Electronics",
    "sale/electronics/audio"=>"Audio",
    "sale/electronics/audio/home"=>"Home Audio",
    "sale/electronics/audio/home/accessories"=>"Home Audio Accessories",
    "sale/electronics/audio/home/amplifier"=>"Amplifiers & Preamps",
    "sale/electronics/audio/home/cassette_deck"=>"Cassette Decks",
    "sale/electronics/audio/home/cd_player"=>"CD Players",
    "sale/electronics/audio/home/equalizer"=>"Equalizers",
    "sale/electronics/audio/home/media"=>"Audio Media",
    "sale/electronics/audio/home/receiver"=>"Receivers",
    "sale/electronics/audio/home/speaker"=>"Speakers",
    "sale/electronics/audio/home/system"=>"Home Theater System",
    "sale/electronics/audio/home/turntable"=>"Turntables",
    "sale/electronics/audio/personal"=>"Personal Audio",
    "sale/electronics/audio/personal/boombox"=>"Boomboxes",
    "sale/electronics/audio/personal/cassette_player"=>"Cassette Players",
    "sale/electronics/audio/personal/cd_player"=>"Personal CD Players",
    "sale/electronics/audio/personal/clock_radio"=>"Clock Radios",
    "sale/electronics/audio/personal/headphone"=>"Headphones",
    "sale/electronics/audio/personal/mp3"=>"MP3 Players",
    "sale/electronics/camera"=>"Cameras",
    "sale/electronics/camera/accessories"=>"Camera Accessories",
    "sale/electronics/camera/accessories/digital"=>"Digital Camera Accessories",
    "sale/electronics/camera/accessories/video"=>"Video Camera Accessories",
    "sale/electronics/camera/digital"=>"Digital Cameras",
    "sale/electronics/camera/film"=>"Film Cameras",
    "sale/electronics/camera/other"=>"Telescopes & Binoculars",
    "sale/electronics/camera/video"=>"Video Camcorders",
    "sale/electronics/car"=>"Car Electronics",
    "sale/electronics/car/gps"=>"Car Navigation Systems",
    "sale/electronics/car/radar"=>"Radar Detectors",
    "sale/electronics/car/stereo"=>"Car Stereo",
    "sale/electronics/dvd"=>"DVD players",
    "sale/electronics/dvr"=>"DVRs",
    "sale/electronics/gps"=>"GPS Devices",
    "sale/electronics/other"=>"Gadgets & Other Electronics",
    "sale/electronics/pda"=>"PDAs",
    "sale/electronics/phone"=>"Phones",
    "sale/electronics/phone/corded"=>"Corded Phones",
    "sale/electronics/phone/cordless"=>"Cordless Phones",
    "sale/electronics/phone/mobile"=>"Mobile Phones",
    "sale/electronics/phone/office"=>"Office Phones",
    "sale/electronics/satellite"=>"Satellite Dishes & Receivers",
    "sale/electronics/tv"=>"Televisions",
    "sale/electronics/vcr"=>"VCRs",
    "sale/entertainment"=>"Entertainment (Movies, Music, Video Games)",
    "sale/entertainment/movie"=>"Movies (DVD & VHS)",
    "sale/entertainment/music"=>"Music",
    "sale/entertainment/video_game"=>"Video Games",
    "sale/free"=>"Free Merchandise",
    "sale/furniture"=>"Furniture",
    "sale/furniture/bed"=>"Beds & Bedroom Sets",
    "sale/furniture/bed/bunk"=>"Bunk Beds",
    "sale/furniture/bed/crib"=>"Cribs",
    "sale/furniture/bed/water"=>"Water Beds",
    "sale/furniture/bench"=>"Benches & Stools",
    "sale/furniture/bench/bench"=>"Benches",
    "sale/furniture/bench/stool"=>"Stools",
    "sale/furniture/bookcase"=>"Bookcases & Shelves",
    "sale/furniture/cabinet"=>"Cabinets, Armoires & Cupboards",
    "sale/furniture/cabinet/armoire"=>"Armoires",
    "sale/furniture/cabinet/cabinet"=>"Cabinets",
    "sale/furniture/cabinet/cupboard"=>"Cupboards",
    "sale/furniture/chair"=>"Chairs",
    "sale/furniture/chair/recliner"=>"Recliner Chairs",
    "sale/furniture/chair/rocking"=>"Rocking Chairs",
    "sale/furniture/desk"=>"Desks",
    "sale/furniture/dresser"=>"Dresser & Vanities",
    "sale/furniture/other"=>"Other Furniture",
    "sale/furniture/other/clock"=>"Clocks",
    "sale/furniture/other/credenza"=>"Credenza",
    "sale/furniture/other/lamp"=>"Lamps",
    "sale/furniture/other/mirror"=>"Mirrors",
    "sale/furniture/rug"=>"Rugs",
    "sale/furniture/sofa"=>"Sofas",
    "sale/furniture/sofa/couch"=>"Couches",
    "sale/furniture/sofa/futon"=>"Futons",
    "sale/furniture/sofa/loveseat"=>"Love Seats",
    "sale/furniture/sofa/sectional"=>"Sectional Sofas",
    "sale/furniture/sofa/sofabed"=>"Sofa Beds & Sleepers",
    "sale/furniture/table"=>"Tables & Stands",
    "sale/furniture/table/changing"=>"Changing Tables",
    "sale/furniture/table/coffee"=>"Coffee Tables",
    "sale/furniture/table/end"=>"End Tables",
    "sale/furniture/table/stand"=>"Stands",
    "sale/health"=>"Health & Beauty",
    "sale/health/cosmetics"=>"Makeup,Cosmetics",
    "sale/health/hair"=>"Hair Products",
    "sale/health/skin_care"=>"Skin Care",
    "sale/home"=>"Home & Garden",
    "sale/home/appliance"=>"Appliances",
    "sale/home/appliance/dishwasher"=>"Dishwashers",
    "sale/home/appliance/microwave"=>"Microwave Ovens",
    "sale/home/appliance/other"=>"Other Appliances",
    "sale/home/appliance/oven"=>"Cooktops, Ovens & Ranges",
    "sale/home/appliance/refrigerator"=>"Refrigerators & Freezers",
    "sale/home/appliance/refrigerator/freezer"=>"Freezers",
    "sale/home/appliance/refrigerator/refrigerator"=>"Refrigerators",
    "sale/home/appliance/small"=>"Small Appliances",
    "sale/home/appliance/small/blender"=>"Blenders",
    "sale/home/appliance/small/bread_machine"=>"Bread Machines",
    "sale/home/appliance/small/coffee_maker"=>"Coffee Makers",
    "sale/home/appliance/small/food_processor"=>"Food Processors",
    "sale/home/appliance/small/juicer"=>"Juicers",
    "sale/home/appliance/small/mixer"=>"Mixers",
    "sale/home/appliance/small/other"=>"Other Small Appliances",
    "sale/home/appliance/small/toaster"=>"Toasters",
    "sale/home/appliance/small/water_filter"=>"Water Filters",
    "sale/home/appliance/washer"=>"Washer & Dryers",
    "sale/home/appliance/washer/dryer"=>"Dryers",
    "sale/home/appliance/washer/washer"=>"Washers",
    "sale/home/appliance/water_heater"=>"Water Heaters",
    "sale/home/bedding"=>"Bedding",
    "sale/home/clean"=>"Cleaning & Vacuuming",
    "sale/home/decor"=>"Home Decor",
    "sale/home/floor"=>"Carpets & Floor Materials",
    "sale/home/food"=>"Food & Produce",
    "sale/home/heat"=>"Heating, Cooling & Air",
    "sale/home/heat/ac"=>"Cooling & Air Conditioners",
    "sale/home/heat/firewood"=>"Firewood & Fuel",
    "sale/home/heat/heat"=>"Heaters, Fireplaces & Furnaces",
    "sale/home/kitchen"=>"Kitchen & Cooking",
    "sale/home/lawn"=>"Lawn, Garden & Patio",
    "sale/home/lawn/lawnmower"=>"Lawnmowers",
    "sale/home/light"=>"Lamps, Lighting & Ceiling Fans",
    "sale/home/pool"=>"Pools, Spas & Hot Tubs",
    "sale/home/security"=>"Home Security",
    "sale/home/tool"=>"Home & Garden Tools",
    "sale/home/tool/hand"=>"Hand Tools",
    "sale/home/tool/hand/axe"=>"Axes",
    "sale/home/tool/hand/chisel"=>"Files & Chisels",
    "sale/home/tool/hand/clamps_vises"=>"Clamps & Vises",
    "sale/home/tool/hand/hammer"=>"Hammers",
    "sale/home/tool/hand/knife"=>"Knives & Cutters",
    "sale/home/tool/hand/ladder"=>"Ladders",
    "sale/home/tool/hand/level"=>"Levels",
    "sale/home/tool/hand/measure"=>"Measuring Tools",
    "sale/home/tool/hand/other"=>"Other Hand Tools",
    "sale/home/tool/hand/plane"=>"Tools: Planes",
    "sale/home/tool/hand/plier"=>"Pliers",
    "sale/home/tool/hand/pry_bar"=>"Pry Bars",
    "sale/home/tool/hand/puller"=>"Tools: Pullers",
    "sale/home/tool/hand/punch"=>"Tools: Punches",
    "sale/home/tool/hand/saw"=>"Saws",
    "sale/home/tool/hand/saw_horse"=>"Sawhorses",
    "sale/home/tool/hand/screwdriver"=>"Screwdrivers",
    "sale/home/tool/hand/sledge_hammer"=>"Sledge Hammers",
    "sale/home/tool/hand/socket"=>"Sockets",
    "sale/home/tool/hand/square"=>"Tools: Squares",
    "sale/home/tool/hand/stud_sensor"=>"Stud Sensors",
    "sale/home/tool/hand/tool_set"=>"Tool Sets",
    "sale/home/tool/hand/wrench"=>"Wrenches",
    "sale/home/tool/other"=>"Other Home Tools",
    "sale/home/tool/power"=>"Power Tools",
    "sale/home/tool/power/air_compress"=>"Air Compressors",
    "sale/home/tool/power/air_hammer"=>"Air Hammers",
    "sale/home/tool/power/air_ratchet"=>"Air Ratchets",
    "sale/home/tool/power/chipper"=>"Wood Chipper",
    "sale/home/tool/power/drill"=>"Drills",
    "sale/home/tool/power/engraver"=>"Engravers",
    "sale/home/tool/power/generator"=>"Generators",
    "sale/home/tool/power/grinder"=>"Grinders",
    "sale/home/tool/power/impact_wrench"=>"Impact Wrenches",
    "sale/home/tool/power/lathe"=>"Lathes",
    "sale/home/tool/power/leaf_blower"=>"Leaf Blower",
    "sale/home/tool/power/nail_gun"=>"Nail & Staple Guns",
    "sale/home/tool/power/planer"=>"Planers",
    "sale/home/tool/power/polisher"=>"Polishers",
    "sale/home/tool/power/pressure_washer"=>"Pressure Washers",
    "sale/home/tool/power/router"=>"Tools: Routers",
    "sale/home/tool/power/sander"=>"Sanders",
    "sale/home/tool/power/saw"=>"Power Saws",
    "sale/home/tool/power/saw/band"=>"Band Saws",
    "sale/home/tool/power/saw/chain"=>"Chain Saws",
    "sale/home/tool/power/saw/circular"=>"Circular Saws",
    "sale/home/tool/power/saw/miter"=>"Miter Saws",
    "sale/home/tool/power/saw/reciprocating"=>"Reciprocating Saws",
    "sale/home/tool/power/saw/scroll"=>"Scroll Saws",
    "sale/home/tool/power/saw/table"=>"Table Saws",
    "sale/home/tool/power/saw/tile"=>"Tile Saws",
    "sale/home/tool/power/welding_soldering"=>"Welding & Soldering",
    "sale/home/tool/wood"=>"Woodworking Tools",
    "sale/home/windows"=>"Windows, Drapes & Curtains",
    "sale/kid"=>"Baby & Kid Stuff",
    "sale/kid/accessories"=>"Baby Grooming, Bathing, and Feeding",
    "sale/kid/backpack"=>"Baby Backpacks & Carriers",
    "sale/kid/bedding"=>"Children's Bedding",
    "sale/kid/bikes"=>"Children's Bikes",
    "sale/kid/books"=>"Children's Books",
    "sale/kid/car_seat"=>"Car Seats",
    "sale/kid/clothes"=>"Children's Clothes",
    "sale/kid/furniture"=>"Children's Furniture",
    "sale/kid/safety"=>"Baby Safety Products",
    "sale/kid/stroller"=>"Baby Strollers",
    "sale/kid/toy"=>"Children's Toys",
    "sale/music"=>"Musical Instruments",
    "sale/music/accessories"=>"Music Accessories",
    "sale/music/accessories/metronome"=>"Metronomes",
    "sale/music/accessories/musicstand"=>"Music Stands",
    "sale/music/accessories/sheetmusic"=>"Sheet Music",
    "sale/music/accessories/tune"=>"Tuning Forks",
    "sale/music/brass"=>"Brass Instruments",
    "sale/music/brass/baritone"=>"Baritones",
    "sale/music/brass/bugle"=>"Bugles",
    "sale/music/brass/cornet"=>"Cornets",
    "sale/music/brass/flugelhorn"=>"Flugelhorns",
    "sale/music/brass/french_horn"=>"French Horns",
    "sale/music/brass/trombone"=>"Trombones",
    "sale/music/brass/trumpet"=>"Trumpets",
    "sale/music/brass/tuba"=>"Tubas",
    "sale/music/drum"=>"Drums & Percussion",
    "sale/music/drum/base"=>"Base Drums",
    "sale/music/drum/bongo"=>"Bongos",
    "sale/music/drum/chimes"=>"Musical Instrument Chimes",
    "sale/music/drum/conga"=>"Conga Drums",
    "sale/music/drum/cowbell"=>"Cowbells",
    "sale/music/drum/cymbal"=>"Cymbals",
    "sale/music/drum/drum"=>"Drums",
    "sale/music/drum/glockespiel"=>"Glockespiels",
    "sale/music/drum/gong"=>"Gongs",
    "sale/music/drum/hi_hat"=>"Hi-Hat Drums",
    "sale/music/drum/maracas"=>"Maracas",
    "sale/music/drum/percussion"=>"Percussions",
    "sale/music/drum/snare"=>"Snare Drums",
    "sale/music/drum/tambourine"=>"Tambourines",
    "sale/music/drum/timpani"=>"Timpanis",
    "sale/music/drum/tomtom"=>"Tom-Tom Drums",
    "sale/music/drum/triangle"=>"Instruments: Triangles",
    "sale/music/drum/xylophone"=>"Xylophones",
    "sale/music/guitar"=>"Guitars & Basses",
    "sale/music/guitar/banjo"=>"Banjos",
    "sale/music/guitar/bass"=>"Bass Instruments",
    "sale/music/guitar/dulcimer"=>"Dulcimers",
    "sale/music/guitar/guitar"=>"Guitars",
    "sale/music/guitar/lute"=>"Lutes",
    "sale/music/guitar/mandolin"=>"Mandolins",
    "sale/music/guitar/ukulele"=>"Ukuleles",
    "sale/music/other"=>"Other Musical Instruments",
    "sale/music/piano"=>"Pianos & Keyboards",
    "sale/music/piano/accordian"=>"Accordians",
    "sale/music/piano/keyboard"=>"Instruments: Keyboards",
    "sale/music/piano/organ"=>"Instruments: Organs",
    "sale/music/piano/piano"=>"Pianos",
    "sale/music/piano/synthesizer"=>"Synthesizers",
    "sale/music/string"=>"Classic Stringed Instruments",
    "sale/music/string/autoharp"=>"Autoharps",
    "sale/music/string/cello"=>"Cellos",
    "sale/music/string/harp"=>"Harps",
    "sale/music/string/viola"=>"Violas",
    "sale/music/string/violin"=>"Violins",
    "sale/music/wind"=>"Woodwinds",
    "sale/music/wind/bassoon"=>"Bassoons",
    "sale/music/wind/clarinet"=>"Clarinets",
    "sale/music/wind/flute"=>"Instruments: Flutes",
    "sale/music/wind/harmonica"=>"Harmonicas",
    "sale/music/wind/oboe"=>"Oboes",
    "sale/music/wind/piccolo"=>"Piccolos",
    "sale/music/wind/recorder"=>"Instruments: Recorders",
    "sale/music/wind/saxophone"=>"Saxophones",
    "sale/other"=>"Everything Else",
    "sale/pet"=>"Pets",
    "sale/pet/bird"=>"Birds",
    "sale/pet/cat"=>"Cats",
    "sale/pet/dog"=>"Dogs",
    "sale/pet/fish"=>"Fish",
    "sale/pet/horse"=>"Horses",
    "sale/pet/livestock"=>"Livestock",
    "sale/pet/livestock/supply"=>"Livestock Supplies",
    "sale/pet/other"=>"Other Pets",
    "sale/pet/rabbit"=>"Rabbits",
    "sale/pet/reptile"=>"Reptiles",
    "sale/pet/small_furry"=>"Small & Furry Animals",
    "sale/pet/supply"=>"Pet Supplies",
    "sale/pet/supply/bird"=>"Pet Supplies, Birds",
    "sale/pet/supply/cat"=>"Pet Supplies, Cats",
    "sale/pet/supply/dog"=>"Pet Supplies, Dogs",
    "sale/pet/supply/fish"=>"Pet Supplies, Fish",
    "sale/pet/supply/horse"=>"Pet Supplies, Horses",
    "sale/sale"=>"Auctions, Estate & Garage Sales",
    "sale/sale/auction"=>"Auctions",
    "sale/sale/estate"=>"Estate Sales",
    "sale/sale/garage"=>"Garage & Yard Sales",
    "sale/sport"=>"Sporting Goods, Bicycles & Equipment",
    "sale/sport/bike"=>"Bicycles & Equipment",
    "sale/sport/bike/apparel"=>"Bicycling Apparel",
    "sale/sport/bike/helmet"=>"Bicycle Helmets",
    "sale/sport/bike/kid"=>"Kids Bikes",
    "sale/sport/bike/mountain"=>"Mountain Bikes",
    "sale/sport/bike/parts"=>"Bicycle Parts & Accessories",
    "sale/sport/bike/road"=>"Road Bikes",
    "sale/sport/camping"=>"Camping Equipment",
    "sale/sport/equestrian"=>"Equestrian Equipment",
    "sale/sport/exercise"=>"Exercise Equipment",
    "sale/sport/exercise/treadmill"=>"Treadmills & Stair Machines",
    "sale/sport/exercise/treadmill/stair"=>"Stair Machines",
    "sale/sport/exercise/treadmill/treadmill"=>"Treadmills",
    "sale/sport/guns"=>"Guns & Rifles",
    "sale/sport/hunting"=>"Hunting & Fishing",
    "sale/sport/hunting/fishing"=>"Fishing Equipment",
    "sale/sport/hunting/hunting"=>"Hunting Equipment",
    "sale/sport/indoor"=>"Indoor Games",
    "sale/sport/indoor/air_hockey"=>"Air Hockey",
    "sale/sport/indoor/darts"=>"Darts",
    "sale/sport/indoor/foosball"=>"Foosball",
    "sale/sport/indoor/ping_pong"=>"Ping Pong",
    "sale/sport/indoor/pool_table"=>"Pool Tables & Equipment",
    "sale/sport/other"=>"Other Sports & Fitness",
    "sale/sport/snow"=>"Snow Sports",
    "sale/sport/snow/ski"=>"Skiing",
    "sale/sport/snow/snowboard"=>"Snowboarding",
    "sale/sport/sport"=>"Sports Equipment",
    "sale/sport/sport/baseball"=>"Baseball Equipment",
    "sale/sport/sport/basketball"=>"Basketball Equipment",
    "sale/sport/sport/football"=>"Football Equipment",
    "sale/sport/sport/golf"=>"Golf Equipment",
    "sale/sport/sport/hockey"=>"Hockey Equipment",
    "sale/sport/sport/other"=>"Other Sports Equipment",
    "sale/sport/sport/soccer"=>"Soccer Equipment",
    "sale/sport/sport/tennis"=>"Tennis & Racquet Sports Equipment",
    "sale/sport/water"=>"Water Sports",
    "sale/sport/water/dive"=>"Scuba & Snorkeling",
    "sale/sport/water/other"=>"Other Water Sports",
    "sale/sport/water/paddle"=>"Canoe, Kayaks, Rafts",
    "sale/sport/water/paddle/canoe"=>"Canoe",
    "sale/sport/water/paddle/kayak"=>"Kayaks",
    "sale/sport/water/paddle/rafts"=>"Rafts",
    "sale/sport/water/ski"=>"Waterskiing & Wakeboarding",
    "sale/sport/water/surf"=>"Surfing",
    "sale/sport/water/wind"=>"Wind Surfing",
    "sale/sport/weight"=>"Weights & Weightlifting Equipment",
    "sale/toy"=>"Crafts, Hobbies & Toys",
    "sale/toy/art"=>"Arts & Crafts Supplies",
    "sale/toy/baby"=>"Infant & Toddler Toys",
    "sale/toy/car"=>"Toy Cars, Trains, Airplanes",
    "sale/toy/dolls"=>"Dolls & Action Figures",
    "sale/toy/educational"=>"Educational Toys",
    "sale/toy/games"=>"Games",
    "sale/toy/outdoor"=>"Outdoor Toys & Structures",
    "sale/toy/stuffed"=>"Stuffed Animals"),
"Tickets"=>array(
    "sale/tickets"=>"Tickets",
    "sale/tickets/concert"=>"Concert Tickets",
    "sale/tickets/group"=>"Group Events",
    "sale/tickets/group/business_networking"=>"Business & Networking Events",
    "sale/tickets/group/class_workshop"=>"Classes & Workshops",
    "sale/tickets/group/conference_seminar"=>"Conferences & Seminars",
    "sale/tickets/group/dance"=>"Dance Events",
    "sale/tickets/group/festival"=>"Festivals",
    "sale/tickets/group/food_wine"=>"Food & Wine Events",
    "sale/tickets/group/free"=>"Free Events",
    "sale/tickets/group/health_spiritual"=>"Health & Spiritual Events",
    "sale/tickets/group/kids_family"=>"Kids & Family Events",
    "sale/tickets/group/other"=>"Other Events",
    "sale/tickets/group/sports_outdoors"=>"Sports & Outdoor Events",
    "sale/tickets/other"=>"Other Tickets",
    "sale/tickets/other/movie"=>"Movie & Film Event Tickets",
    "sale/tickets/other/travel"=>"Travel Tickets",
    "sale/tickets/sports"=>"Sports Tickets",
    "sale/tickets/sports/auto_racing"=>"Auto Racing Tickets",
    "sale/tickets/sports/baseball"=>"Baseball Tickets",
    "sale/tickets/sports/basketball"=>"Basketball Tickets",
    "sale/tickets/sports/boxing"=>"Boxing Tickets",
    "sale/tickets/sports/cricket"=>"Cricket Tickets",
    "sale/tickets/sports/football"=>"Football Tickets",
    "sale/tickets/sports/golf"=>"Golf Tickets",
    "sale/tickets/sports/hockey"=>"Hockey Tickets",
    "sale/tickets/sports/horse_racing"=>"Horse Racing Tickets",
    "sale/tickets/sports/olympics"=>"Olympics Tickets",
    "sale/tickets/sports/other"=>"Other Sports Tickets",
    "sale/tickets/sports/rugby"=>"Rugby Tickets",
    "sale/tickets/sports/soccer"=>"Soccer Tickets",
    "sale/tickets/sports/tennis"=>"Tennis Tickets",
    "sale/tickets/sports/track_field"=>"Track and Field Tickets",
    "sale/tickets/sports/wrestling"=>"Wrestling Tickets",
    "sale/tickets/theater"=>"Theater Tickets"),
"Services"=>array(
    "service"=>"Services",
    "service/car"=>"Auto & Other Vehicle Services",
    "service/car/detailing"=>"Auto Detailing & Cleaning",
    "service/car/oil_change"=>"Auto Lube & Oil Change",
    "service/car/rental"=>"Vehicles for Rent",
    "service/car/repair"=>"Auto Repair",
    "service/car/tires"=>"Auto Tire Services",
    "service/care"=>"Child & Elderly Care Services",
    "service/care/child"=>"Child Care",
    "service/care/child/babysitter"=>"Babysitters",
    "service/care/child_safety"=>"Child Safety Services",
    "service/care/elderly"=>"Elderly Care",
    "service/care/nurse"=>"Home Nurse",
    "service/cleaning"=>"Cleaning Services",
    "service/cleaning/carpet"=>"Carpet & Upholstery Cleaning",
    "service/cleaning/chimney"=>"Chimney & Fireplace Cleaning",
    "service/cleaning/exterior"=>"Exterior Home Cleaning",
    "service/cleaning/interior"=>"Home Cleaning & Maid Services",
    "service/cleaning/junk"=>"Removal of Junk or Building Materials",
    "service/cleaning/window"=>"Window Cleaning",
    "service/coupon"=>"Coupons & Offers",
    "service/coupon/art"=>"Art and Collectibles",
    "service/coupon/book"=>"Books and Magazines",
    "service/coupon/car"=>"Automotive",
    "service/coupon/clothes"=>"Clothing and Accessories",
    "service/coupon/dining"=>"Dining",
    "service/coupon/education"=>"Education and Learning",
    "service/coupon/electronics"=>"Computers and Electronics",
    "service/coupon/entertainment"=>"Entertainment",
    "service/coupon/food"=>"Groceries",
    "service/coupon/gift"=>"Gifts, Flowers and Gourmet Foods",
    "service/coupon/health"=>"Health and Beauty",
    "service/coupon/home"=>"Home and Garden",
    "service/coupon/kid"=>"Baby and Kids",
    "service/coupon/office"=>"Office and Business",
    "service/coupon/other"=>"Other",
    "service/coupon/pet"=>"Pet Products and Services",
    "service/coupon/phone"=>"Phone and Internet Services",
    "service/coupon/service"=>"Services",
    "service/coupon/sport"=>"Sports and Fitness",
    "service/coupon/travel"=>"Travel",
    "service/creative"=>"Creative Services",
    "service/creative/design"=>"Design Services",
    "service/creative/film"=>"Film/Production Services",
    "service/creative/music"=>"Recording Services",
    "service/creative/other"=>"Other Creative",
    "service/creative/photo"=>"Photographic Services",
    "service/education"=>"Lessons & Classes",
    "service/education/art"=>"Arts & Craft Lessons",
    "service/education/cooking"=>"Cooking Classes",
    "service/education/dance"=>"Dance Lessons",
    "service/education/driving"=>"Driving Instruction",
    "service/education/language"=>"Language Lessons",
    "service/education/music"=>"Music Lessons",
    "service/education/other"=>"Other Lessons & Classes",
    "service/education/school"=>"Instruction Schools",
    "service/education/sports"=>"Sports Lessons",
    "service/education/sports/golf"=>"Golf Lessons",
    "service/education/tech"=>"Technology Classes",
    "service/education/tutor"=>"Private Instruction & Tutoring",
    "service/entertainment"=>"Party & Entertainment Services",
    "service/entertainment/catering"=>"Catering",
    "service/entertainment/event"=>"Event Planners",
    "service/entertainment/kid"=>"Kids Parties",
    "service/entertainment/music"=>"Music & DJs",
    "service/entertainment/other"=>"Other Party & Entertainment Services",
    "service/entertainment/rental"=>"Party Rentals",
    "service/finance"=>"Financial & Legal Services",
    "service/finance/accountant"=>"Accounting & Bookkeeping",
    "service/finance/credit"=>"Help with Credit",
    "service/finance/financial"=>"Financial Advisors",
    "service/finance/insurance"=>"Insurance",
    "service/finance/investments"=>"Investment Services",
    "service/finance/loans"=>"Financial Loans",
    "service/finance/loans/auto"=>"Auto Loans",
    "service/finance/loans/home"=>"Home Loans",
    "service/finance/other"=>"Other Financial & Legal Services",
    "service/finance/tax"=>"Tax Preparation",
    "service/food"=>"Restaurants, Clubs & Food",
    "service/food/bar"=>"Bars, Pubs & Clubs",
    "service/food/restaurant"=>"Restaurants",
    "service/health"=>"Health & Beauty Services",
    "service/health/alternative"=>"Alternative Medicine",
    "service/health/art"=>"Body Art",
    "service/health/chiropractor"=>"Chiropractors",
    "service/health/counseling"=>"Counseling",
    "service/health/fitness"=>"Exercise & Fitness Services",
    "service/health/hair"=>"Hair Care & Styling",
    "service/health/massage"=>"Massage Services",
    "service/health/medical"=>"Medical Care",
    "service/health/other"=>"Other Health & Beauty Services",
    "service/health/pedicure"=>"Manicure & Pedicure",
    "service/health/skin_care"=>"Skin Care, Cosmetics & Tanning",
    "service/home"=>"Home Repair & Maintenance",
    "service/home/appliance"=>"Appliance Repair & Installation",
    "service/home/appliance/install"=>"Appliance Installation",
    "service/home/appliance/repair"=>"Appliance Repair or Service",
    "service/home/construction"=>"Construction & Remodeling",
    "service/home/construction/addition"=>"Home Additions",
    "service/home/construction/demolition"=>"Demolition",
    "service/home/construction/new"=>"New Home Construction",
    "service/home/construction/professional"=>"Home Construction Professionals",
    "service/home/construction/professional/appraiser"=>"Appraisers",
    "service/home/construction/professional/architect"=>"Architects",
    "service/home/construction/professional/engineer"=>"Engineers",
    "service/home/construction/professional/other"=>"Other Construction Professionals",
    "service/home/construction/professional/survey"=>"Land Surveyor",
    "service/home/construction/remodel"=>"Home Remodels & Renovations",
    "service/home/construction/sheds"=>"Sheds & Exterior Structures",
    "service/home/decor"=>"Home Decorating Services",
    "service/home/door"=>"Windows & Doors",
    "service/home/door/cover"=>"Awning & Patio Cover Services",
    "service/home/door/door"=>"Door Installation & Repair",
    "service/home/door/garage"=>"Garage Door Installation & Repair",
    "service/home/door/locks_screens"=>"Door Hardware, Locks & Screens",
    "service/home/door/window"=>"Window Sales, Installation & Repair",
    "service/home/door/window/tinting"=>"Window Protection & Tinting",
    "service/home/door/window/treatment"=>"Window Treatment Services",
    "service/home/electrical"=>"Electrical & Lighting Services",
    "service/home/electrical/electrical"=>"Electrical Services",
    "service/home/electrical/generator"=>"Generator Installation & Repair",
    "service/home/electrical/lighting"=>"Lighting Design & Installation",
    "service/home/electrical/lighting/holiday"=>"Holiday Lighting Services",
    "service/home/electrical/security"=>"Home Security & Alarm Services",
    "service/home/floor"=>"Flooring",
    "service/home/floor/carpet"=>"Carpet Installation",
    "service/home/floor/concrete"=>"Concrete Floors",
    "service/home/floor/rock"=>"Brick & Stone Floors",
    "service/home/floor/sport"=>"Sport Surfaces",
    "service/home/floor/tile"=>"Tile Flooring",
    "service/home/floor/vinyl"=>"Vinyl & Laminate Floors",
    "service/home/floor/wood"=>"Hardwood Floors",
    "service/home/furniture"=>"Furniture Repair & Upholstery",
    "service/home/furniture/repair"=>"Furniture Repair",
    "service/home/furniture/upholstry"=>"Upholstery",
    "service/home/handyman"=>"Handyman Services",
    "service/home/heat"=>"Heating & Cooling Services",
    "service/home/heat/ac"=>"Air Conditioning & Cooling",
    "service/home/heat/central"=>"Central Heating Systems",
    "service/home/heat/ducts"=>"Ducts & Vents",
    "service/home/heat/fan"=>"Fans",
    "service/home/heat/fireplace"=>"Gas Fireplaces & Inserts",
    "service/home/heat/fuel"=>"Fuel Delivery & Storage",
    "service/home/heat/furnace"=>"Furnace, Boilers & Radiators",
    "service/home/heat/hvac"=>"Other HVAC",
    "service/home/heat/radiant"=>"Radiant Heat Systems",
    "service/home/heat/thermostat"=>"Thermostats & Accessories",
    "service/home/heat/water"=>"Water Heater Services",
    "service/home/other"=>"Other Home Services",
    "service/home/other/disable"=>"Home Disability Services",
    "service/home/other/green"=>"Asbestos, Lead, Mold & Radon Services",
    "service/home/other/metal"=>"Metal Work & Sign Makers",
    "service/home/other/pest_control"=>"Pest Control",
    "service/home/other/recovery"=>"Recovery Services",
    "service/home/other/rental"=>"Home Service Rentals",
    "service/home/other/security"=>"Home Security & Safety",
    "service/home/paint"=>"Painting & Staining Services",
    "service/home/paint/exterior"=>"Exterior Painting or Staining",
    "service/home/paint/interior"=>"Interior Painting or Staining",
    "service/home/paint/removal"=>"Paint Removal & Cleaning",
    "service/home/paint/special"=>"Special Paint Finishes",
    "service/home/plumbing"=>"Plumbing Services",
    "service/home/plumbing/drain"=>"Drain Clearing",
    "service/home/plumbing/fire_sprinkler"=>"Fire Sprinkler Systems",
    "service/home/plumbing/fixtures"=>"Faucets, Fixtures & Pipes",
    "service/home/plumbing/other"=>"Other Plumbing Related Services",
    "service/home/plumbing/pump"=>"Plumbing Pump Services",
    "service/home/plumbing/septic"=>"Septic & Sewer Systems",
    "service/home/plumbing/water_softener"=>"Water Softening & Purification",
    "service/home/rock"=>"Concrete, Stone & Brick",
    "service/home/rock/driveway"=>"Driveways, Patios & Walks",
    "service/home/rock/fireplace"=>"Chimney, Fireplace, Stove & BBQ",
    "service/home/rock/floor"=>"Foundations",
    "service/home/rock/other"=>"Other Concrete & Masonry Services",
    "service/home/roof"=>"Roofing, Siding & Gutters",
    "service/home/roof/cleaning"=>"Gutter Cleaning",
    "service/home/roof/gutter"=>"Gutter Installation & Repair",
    "service/home/roof/new"=>"Roof Sales & Installation",
    "service/home/roof/repair"=>"Roof Repair",
    "service/home/roof/siding"=>"Siding Installation & Repair",
    "service/home/roof/skylight"=>"Skylight Installation & Repair",
    "service/home/wall"=>"Wall & Ceiling Services",
    "service/home/wall/ceiling"=>"Ceilings",
    "service/home/wall/drywall"=>"Drywall & Plaster",
    "service/home/wall/insulation"=>"Insulation",
    "service/home/wall/wallpaper"=>"Wallpapering",
    "service/home/wood"=>"Carpentry & Cabinets",
    "service/home/wood/cabinet"=>"Cabinetry Services",
    "service/home/wood/closet"=>"Closet Design & Installation",
    "service/home/wood/countertop"=>"Countertops",
    "service/home/wood/finish"=>"Finish Carpentry",
    "service/home/wood/frame"=>"House Framing",
    "service/home/wood/stair"=>"Stairs & Railings",
    "service/job"=>"Career Services",
    "service/lawn"=>"Lawn & Garden Services",
    "service/lawn/blacktop"=>"Blacktop & Paving",
    "service/lawn/deck"=>"Decks",
    "service/lawn/fence"=>"Fences",
    "service/lawn/fountain"=>"Fountains, Ponds & Water Features",
    "service/lawn/gardener"=>"Lawn Care & Gardening",
    "service/lawn/landscape"=>"Landscaping",
    "service/lawn/landscape/design"=>"Design & Installation",
    "service/lawn/landscape/sprinkler"=>"Sprinkler Systems",
    "service/lawn/other"=>"Other Lawn & Garden Services",
    "service/lawn/rock"=>"Hardscaping",
    "service/lawn/rock/patio"=>"Outdoor Patios, Steps & Walkways",
    "service/lawn/rock/wall"=>"Outdoor Walls & Retaining Walls",
    "service/lawn/snow_removal"=>"Snow Removal",
    "service/lawn/tree"=>"Tree & Shrub Service",
    "service/legal"=>"Legal Services",
    "service/move"=>"Moving & Storage Services",
    "service/move/hauler"=>"Hauling",
    "service/move/mover"=>"Moving",
    "service/move/storage"=>"Storage",
    "service/other"=>"Other Services",
    "service/other/special"=>"Special Offers on Services",
    "service/pet"=>"Pet & Animal Services",
    "service/pet/grooming"=>"Washing & Grooming",
    "service/pet/kennel"=>"Kennels",
    "service/pet/other"=>"Other Pet Services",
    "service/pet/sitter"=>"Pet Sitting",
    "service/pet/veterinarian"=>"Veterinarians",
    "service/pet/walker"=>"Dog Walking",
    "service/pool"=>"Pool, Spa & Sauna Services",
    "service/pool/pool"=>"Swimming Pools",
    "service/pool/pool/maintenance"=>"Pool Maintenance",
    "service/pool/pool/new"=>"Pool Sales & Installation",
    "service/pool/pool/repair"=>"Pool Repair",
    "service/pool/sauna"=>"Saunas",
    "service/pool/sauna/maintenance"=>"Sauna Maintenance",
    "service/pool/sauna/new"=>"Sauna Sales & Installation",
    "service/pool/sauna/repair"=>"Sauna Repair",
    "service/pool/tub"=>"Hot Tubs & Spas",
    "service/pool/tub/maintenance"=>"Spa Maintenance",
    "service/pool/tub/new"=>"Spa Sales & Installation",
    "service/pool/tub/repair"=>"Spa Repair",
    "service/real_estate"=>"Real Estate Agents & Services",
    "service/real_estate/agent"=>"Real Estate Agents & Brokers",
    "service/real_estate/appraiser"=>"Appraisal Services",
    "service/real_estate/inspector"=>"Home Inspectors",
    "service/real_estate/inspector/pest"=>"Pest Inspectors",
    "service/real_estate/inspector/roof"=>"Roof Inspectors",
    "service/real_estate/inspector/water"=>"Waterproofing Inspectors",
    "service/real_estate/other"=>"Other Real Estate Services",
    "service/real_estate/staging"=>"Staging Services",
    "service/tech"=>"Technical Repair & Services",
    "service/tech/audio_video"=>"Audio & Video Setup & Repair",
    "service/tech/computer"=>"Computer Setup & Repair",
    "service/tech/home_network"=>"Home Networking Services",
    "service/tech/repair"=>"Electronics Repair",
    "service/transportation"=>"Travel & Transportation Services",
    "service/transportation/transportation"=>"Transportation Services",
    "service/transportation/travel"=>"Travel Services"),
"Cars_Vehicles"=>array(
    "vehicle"=>"Cars & Vehicles",
    "vehicle/airplane"=>"Airplanes & Aviation",
    "vehicle/boat"=>"Boats",
    "vehicle/boat/fishing"=>"Fishing Boats",
    "vehicle/boat/jetski"=>"JetSkis & Watercraft",
    "vehicle/boat/motor"=>"Motorboats & Powerboats",
    "vehicle/boat/sailboat"=>"Sailboats",
    "vehicle/boat/yacht"=>"Yachts",
    "vehicle/car"=>"Cars",
    "vehicle/car/convertible"=>"Convertibles",
    "vehicle/car/coupe"=>"Coupes",
    "vehicle/car/hybrid"=>"Hybrids",
    "vehicle/car/mini_van"=>"Mini-Vans",
    "vehicle/car/sedan"=>"Sedans",
    "vehicle/car/station_wagon"=>"Station Wagons",
    "vehicle/car/suv"=>"SUVs",
    "vehicle/car/truck"=>"Trucks",
    "vehicle/car/van"=>"Vans",
    "vehicle/commercial_truck"=>"Commercial Trucks & Trailers",
    "vehicle/commercial_truck/auto_carrier"=>"Auto Carrier Trucks",
    "vehicle/commercial_truck/bucket"=>"Bucket Trucks",
    "vehicle/commercial_truck/cab_and_chassis"=>"Truck Cabs & Chassis",
    "vehicle/commercial_truck/cabover"=>"Cabover Trucks",
    "vehicle/commercial_truck/cabover/sleeper"=>"Cabover Sleeper Trucks",
    "vehicle/commercial_truck/construction_vocational"=>"Construction & Vocational Trucks",
    "vehicle/commercial_truck/conventional_sleeper"=>"Conventional Sleeper Trucks",
    "vehicle/commercial_truck/crane"=>"Crane Trucks",
    "vehicle/commercial_truck/day_cab"=>"Day Cab Trucks",
    "vehicle/commercial_truck/dump"=>"Dump Trucks",
    "vehicle/commercial_truck/expeditor_hot_shot"=>"Expeditor & Hot Shot Trucks",
    "vehicle/commercial_truck/flatbed"=>"Flatbed Trucks",
    "vehicle/commercial_truck/grain"=>"Grain Trucks",
    "vehicle/commercial_truck/logging"=>"Logging Trucks",
    "vehicle/commercial_truck/mixers"=>"Mixer Trucks",
    "vehicle/commercial_truck/other"=>"Other Commercial Trucks",
    "vehicle/commercial_truck/refridgerated"=>"Refrigerated Trucks",
    "vehicle/commercial_truck/refuse"=>"Refuse Trucks",
    "vehicle/commercial_truck/refuse/front_loading"=>"Front-Loading Refuse Trucks",
    "vehicle/commercial_truck/refuse/rear_loading"=>"Rear-Loading Refuse Trucks",
    "vehicle/commercial_truck/refuse/recycling"=>"Recycling Trucks",
    "vehicle/commercial_truck/rollback"=>"Rollback Trucks",
    "vehicle/commercial_truck/rolloff"=>"Roll Off Trucks",
    "vehicle/commercial_truck/service_utility"=>"Service & Utility Trucks",
    "vehicle/commercial_truck/severe_duty"=>"Severe Duty Trucks",
    "vehicle/commercial_truck/tank"=>"Tank Trucks",
    "vehicle/commercial_truck/tow"=>"Tow Trucks",
    "vehicle/commercial_truck/trailer"=>"Commercial Truck Trailers",
    "vehicle/commercial_truck/trailer/beam"=>"Beam Trailers",
    "vehicle/commercial_truck/trailer/belt"=>"Belt Trailers",
    "vehicle/commercial_truck/trailer/car_carrier"=>"Car Carrier Trailers",
    "vehicle/commercial_truck/trailer/chassis"=>"Chassis Trailers",
    "vehicle/commercial_truck/trailer/container"=>"Container Trailers",
    "vehicle/commercial_truck/trailer/converter_dollies"=>"Flip, Converter Dollies & Jeep Trailers",
    "vehicle/commercial_truck/trailer/curtainside"=>"Curtainside Trailers",
    "vehicle/commercial_truck/trailer/drop_deck"=>"Drop Deck Trailers",
    "vehicle/commercial_truck/trailer/drop_deck/double"=>"Double Drop Trailers",
    "vehicle/commercial_truck/trailer/drop_deck/expandable"=>"Expandable Drop Deck Trailers",
    "vehicle/commercial_truck/trailer/drop_deck/expandable_double"=>"Expandable Double Drop Trailers",
    "vehicle/commercial_truck/trailer/dump"=>"Dump Trailers",
    "vehicle/commercial_truck/trailer/equipment"=>"Equipment Trailers",
    "vehicle/commercial_truck/trailer/flatbed"=>"Flatbed Trailers",
    "vehicle/commercial_truck/trailer/flatbed/expandable"=>"Expandable Flatbed Trailers",
    "vehicle/commercial_truck/trailer/grain"=>"Grain Trailers",
    "vehicle/commercial_truck/trailer/hopper"=>"Hopper Trailers",
    "vehicle/commercial_truck/trailer/livestock"=>"Horse & Livestock Trailers",
    "vehicle/commercial_truck/trailer/log"=>"Log Trailers",
    "vehicle/commercial_truck/trailer/lowboy"=>"Lowboy Trailers",
    "vehicle/commercial_truck/trailer/open_top"=>"Open Top Trailers",
    "vehicle/commercial_truck/trailer/other"=>"Other Trailers",
    "vehicle/commercial_truck/trailer/platform"=>"Platform Trailers",
    "vehicle/commercial_truck/trailer/reefer"=>"Reefer Trailers",
    "vehicle/commercial_truck/trailer/rolloff"=>"Roll Off Trailers",
    "vehicle/commercial_truck/trailer/specialty"=>"Specialty Trailers",
    "vehicle/commercial_truck/trailer/storage"=>"Storage Trailers",
    "vehicle/commercial_truck/trailer/tag"=>"Tag Trailers",
    "vehicle/commercial_truck/trailer/tank"=>"Tank Trailers",
    "vehicle/commercial_truck/trailer/van"=>"Van Trailers",
    "vehicle/commercial_truck/van"=>"Van Trucks",
    "vehicle/commercial_truck/yard"=>"Yard Trucks",
    "vehicle/heavy_equipment"=>"Heavy Equipment Vehicles",
    "vehicle/motorcycle"=>"Motorcycles",
    "vehicle/motorcycle/offroad"=>"Dirt & Offroad Bikes",
    "vehicle/motorcycle/road"=>"Road Motor Bikes",
    "vehicle/motorcycle/scooter"=>"Scooters & Mopeds",
    "vehicle/other"=>"Other Vehicles",
    "vehicle/parts"=>"Vehicle Parts, Accessories & Storage",
    "vehicle/parts/airplane"=>"Aviation Parts & Accessories",
    "vehicle/parts/airplane/accessories"=>"Aviation Accessories",
    "vehicle/parts/airplane/parts"=>"Aviation Parts",
    "vehicle/parts/airplane/storage"=>"Aviation Storage",
    "vehicle/parts/atv"=>"ATV Parts & Accessories",
    "vehicle/parts/boat"=>"Boat Parts & Accessories",
    "vehicle/parts/boat/accessories"=>"Boat Accessories",
    "vehicle/parts/boat/parts"=>"Boat Motors & Parts",
    "vehicle/parts/boat/storage"=>"Boat Storage",
    "vehicle/parts/car"=>"Car & Truck Parts & Accessories",
    "vehicle/parts/car/accessories"=>"Car & Truck Accessories",
    "vehicle/parts/car/parts"=>"Car & Truck Parts",
    "vehicle/parts/motorcycle"=>"Motorcycle Parts & Accessories",
    "vehicle/parts/rv"=>"RV Parts & Accessories",
    "vehicle/parts/rv/accessories"=>"RV Accessories",
    "vehicle/parts/rv/parts"=>"RV Motors & Parts",
    "vehicle/parts/rv/spaces"=>"RV Parks & Spaces",
    "vehicle/parts/snowmobile"=>"Snowmobile Parts & Accessories",
    "vehicle/powersports"=>"Power Sports",
    "vehicle/powersports/atv"=>"ATVs",
    "vehicle/powersports/snowmobile"=>"Snowmobiles",
    "vehicle/rv"=>"RVs & Motor Homes")
);
?>
